CACHE_TYPE = 'SimpleCache'
CACHE_DEFAULT_TIMEOUT = 1800
DEBUG = True
SECRET_KEY = '4fc189e327eccghdslfghio4a72'
MAX_CONTENT_LENGTH = 1024 * 1024
SQLALCHEMY_DATABASE_URI = 'sqlite:///tasker.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False